In [1]:
import pandas as pd

In [5]:
pd.read_json("C:\\Users\\jiyad\\Downloads\\archive (11)\\train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [8]:
import pandas as pd

In [1]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 1.9 MB/s eta 0:00:06
     --- ------------------------------------ 1.0/11.9 MB 2.2 MB/s eta 0:00:05
     ----- ---------------------------------- 1.6/11.9 MB 2.4 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.3 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.3 MB/s eta 0:00:05
     --------- ------------------------------ 2.9/11.9 MB 2.1 MB/s eta 0:00:05
     ---------- ----------------------------- 3.1/11.9 MB 2.1 MB/s eta 0:00:05
     ------------- -------------------------- 3.9/11.9 MB 2.2 MB/s eta 0:00:04
     --------------- ------------------------ 4.7/11.9 MB 2.3 MB/s eta 0:00:04
     ----------------- ---------------------- 5.2/11.9 MB 2.3 MB/s eta 0:00:03
     ------------------ --------------------- 5.5/11.9 MB 2.3 MB/s eta 0:00:03
     ------------------ --------------------- 5.5/11.9 MB 2.3 MB/s eta 0:00:03
     --------------------- ------------------ 6.3/11.9 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 6.6/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 2.2 MB/s eta 0:00:03
     ------------------------- -------------- 7.6/11.9 MB 2.2 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 2.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 2.1 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 2.1 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 2.1 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 2.1 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 2.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 2.2 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.1 MB/s  0:00:05
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp314-cp314-win_amd64.whl size=248718 sha256=3dbfed803b644081f452f9dc8970b37d5acacd76182ba76ff152dc2557c19b48
  Stored in directory: c:\users\jiyad\appdata\local\pip\cache\wheels\a2\5a\60\e03682d488f501428666827b000cfa0da00163afcd74ce2c14
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [2]:
import mysql.connector

In [6]:
conn = mysql.connector.connect(host='localhost', user = 'root', password = '', database = 'World')

In [11]:
pd.read_sql_query("SELECT * FROM city ", conn)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_17196\3818667837.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city ", conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [15]:
pd.read_sql_query("SELECT * FROM city WHERE District = 'Kabol' OR CountryCode = 'AFG'", conn)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_17196\3798659095.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE District = 'Kabol' OR CountryCode = 'AFG'", conn)

   ID            Name CountryCode  District  Population
0   1           Kabul         AFG     Kabol     1780000
1   2        Qandahar         AFG  Qandahar      237500
2   3           Herat         AFG     Herat      186800
3   4  Mazar-e-Sharif         AFG     Balkh      127800

In [17]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode Like 'IND'", conn)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_17196\951274465.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode Like 'IND'", conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [18]:
pd.read_sql_query("SELECT * FROM country ", conn)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_17196\35400287.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country ", conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [23]:
pd.read_sql_query("SELECT * FROM country WHERE LocalName LIKE 'A%a' AND Code like 'A%'", conn)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_17196\1109911641.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE LocalName LIKE 'A%a' AND Code like 'A%'", conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56,AO
2,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
4,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65,AE
5,ARG,Argentina,South America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rúa,69,AR
6,ASM,American Samoa,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,US Territory,George W. Bush,54,AS
7,ATG,Antigua and Barbuda,North America,Caribbean,442.0,1981.0,68000,70.5,612.0,584.0,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63,AG
8,AUS,Australia,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135,AU

In [24]:
pd.read_sql_query("SELECT * FROM Countrylanguage ", conn)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_17196\4103331087.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM Countrylanguage ", conn)

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [25]:
pd.read_sql_query("SELECT * FROM Countrylanguage WHERE IsOfficial LIKE 'T'", conn)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_17196\1185896715.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM Countrylanguage WHERE IsOfficial LIKE 'T'", conn)

    CountryCode   Language IsOfficial  Percentage
0           ABW      Dutch          T         5.3
1           AFG       Dari          T        32.1
2           AFG     Pashto          T        52.4
3           AIA    English          T         0.0
4           ALB  Albaniana          T        97.9
..          ...        ...        ...         ...
233         ZAF  Afrikaans          T        14.3
234         ZAF    English          T         8.5
235         ZAF      Xhosa          T        17.7
236         ZAF       Zulu          T        22.7
237         ZWE    English          T         2.2

[238 rows x 4 columns]

In [2]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Jiya@0937",
    database="MYSQL",
    port=3306
)

cursor = conn.cursor()
print("✅ MySQL connected successfully")

✅ MySQL connected successfully