# Import libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Data Collectionn and analysis

In [2]:
df = pd.read_csv("diabetes.csv")
df.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
205,5,111,72,28,0,23.9,0.407,27,0
371,0,118,64,23,89,0.0,1.731,21,0
697,0,99,0,0,0,25.0,0.253,22,0
704,4,110,76,20,100,28.4,0.118,27,0
435,0,141,0,0,0,42.4,0.205,29,1

In [3]:
df.shape

(768, 9)

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
df['Outcome'].value_counts()

# 0 -> Non Diebetes
# 1 -> Diebetes

Outcome
0    500
1    268
Name: count, dtype: int64

# train test split

In [7]:

X = df.drop(columns = 'Outcome', axis = 1)
Y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 2)

In [8]:
X_train.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
501,3,84,72,32,0,37.2,0.267,28
371,0,118,64,23,89,0.0,1.731,21
634,10,92,62,0,0,25.9,0.167,31
221,2,158,90,0,0,31.6,0.805,66
12,10,139,80,0,0,27.1,1.441,57

In [18]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(537, 8) (537,)
(231, 8) (231,)

# Standerization

In [10]:
scaler = StandardScaler()

scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
X_train_scaled

array([[-2.88114829e-01, -1.22309245e+00,  1.29331617e-01, ...,
         6.79078156e-01, -6.27909087e-01, -4.56474754e-01],
       [-1.17053496e+00, -1.33658264e-01, -2.97731125e-01, ...,
        -4.06810020e+00,  3.52432104e+00, -1.05392900e+00],
       [ 1.77086548e+00, -9.66754997e-01, -4.04496811e-01, ...,
        -7.62941076e-01, -9.11531363e-01, -2.00422933e-01],
       ...,
       [ 6.02521506e-03,  9.06370102e-02,  2.25659317e-02, ...,
        -3.80104112e-01,  1.85945828e+00,  9.94485562e-01],
       [-2.88114829e-01, -1.97742628e-01,  2.36097303e-01, ...,
        -7.11896147e-01, -1.08170473e+00, -7.97877181e-01],
       [ 6.02521506e-03, -3.89995720e-01, -1.90965440e-01, ...,
         2.73285232e-03, -4.93196428e-02, -3.71124147e-01]])

In [12]:
X_train_data = pd.DataFrame(X_train_scaled, columns = X_train.columns)
X_test_data = pd.DataFrame(X_test_scaled, columns = X_test.columns)

In [13]:
X_train_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,-0.288115,-1.223092,0.129332,0.731398,-0.709554,0.679078,-0.627909,-0.456475
1,-1.170535,-0.133658,-0.297731,0.165460,0.029457,-4.068100,3.524321,-1.053929
2,1.770865,-0.966755,-0.404497,-1.280825,-0.709554,-0.762941,-0.911531,-0.200423
3,-0.582255,1.148029,1.090223,-1.280825,-0.709554,-0.035551,0.897979,2.786848
4,1.770865,0.539228,0.556394,-1.280825,-0.709554,-0.609806,2.701816,2.018693

# Train the Model

In [15]:
classifier = svm.SVC(kernel = 'linear')

# training the support vector Machine Classifier
classifier.fit(X_train, y_train)

SVC(kernel='linear')

# Model Evaluation

In [28]:
# accuracy of the trianed data
X_train_prediction = classifier.predict(X_train)

# find Accuracy of the trianing data
training_Data_accuracy = accuracy_score(X_train_prediction, y_train)
training_Data_accuracy

0.7821229050279329

In [30]:
# accuracy of the testing data
X_test_prediction = classifier.predict(X_test)

# find the Acuuracy Score of the testing data
testing_data_accuracy = accuracy_score(X_test_prediction, y_test)
testing_data_accuracy

0.7532467532467533

In [59]:
# Making the input data
input_data = 1,85,66,29,0,26.6,0.351,31

# changing the input_Data to numpy array
input_data_as_numpy_array = np.asarray(input_data)    

input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
std_data = scaler.transform(input_data_reshaped)


# Input data prediction
input_Data_prediction = classifier.predict(std_data)
if input_Data_prediction == 1:
    print("yes, patient has a diebetes")
else:
    print("No, patient does not have diebetes")

No, patient does not have diebetes

C:\Users\jiyad\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\jiyad\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(