In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [2]:
house_data = pd.read_csv("data.csv")
house_data.sample(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
2012,2014-06-05 00:00:00,324500.0,3.0,2.50,1660,3990,2.0,0,0,3,1660,0,2009,0,8132 Wolcott Ave S,Seattle,WA 98118,USA
430,2014-05-09 00:00:00,583000.0,4.0,2.50,2660,4000,2.0,0,0,3,2660,0,2001,0,9921 227th Way NE,Redmond,WA 98053,USA
3067,2014-06-23 00:00:00,649950.0,3.0,2.50,1500,1375,2.0,0,0,3,1200,300,2014,0,2811 14th Ave W,Seattle,WA 98119,USA
1656,2014-05-31 00:00:00,587000.0,4.0,2.50,2550,6256,2.0,0,0,3,2550,0,1992,0,13013 NE 202nd Pl,Woodinville,WA 98072,USA
2397,2014-06-12 00:00:00,706000.0,3.0,2.75,1900,6400,1.0,0,0,5,1410,490,1942,0,4324 NE 56th St,Seattle,WA 98105,USA

# Features Analysis

In [3]:
house_data.info

<bound method DataFrame.info of                      date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940
...                   ...           ...       ...        ...          ...
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340
1         9050     2.0           0     4          5        3370
2        11947     1.0           0     0          4        1930
3         8030     1.0           0     0          4        1000
4        10500     1.0           0     0          4        1140
...        ...     ...         ...   ...        ...         ...
4595      6360     1.0           0     0          4        1510
4596      7573     2.0           0     0          3        1460
4597      7014     2.0           0     0          3        3010
4598      6630     1.0           0     0          3        1070
4599      8102     2.0           0     0          4        1490

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N
1               280      1921             0           709 W Blaine St
2                 0      1966             0  26206-26214 143rd Ave SE
3              1000      1963             0           857 170th Pl NE
4               800      1976          1992         9105 170th Ave NE
...             ...       ...           ...                       ...
4595              0      1954          1979            501 N 143rd St
4596              0      1983          2009          14855 SE 10th Pl
4597              0      2009             0          759 Ilwaco Pl NE
4598           1020      1974             0         5148 S Creston St
4599              0      1990             0         18717 SE 258th St

           city  statezip country
0     Shoreline  WA 98133     USA
1       Seattle  WA 98119     USA
2          Kent  WA 98042     USA
3      Bellevue  WA 98008     USA
4       Redmond  WA 98052     USA
...         ...       ...     ...
4595    Seattle  WA 98133     USA
4596   Bellevue  WA 98007     USA
4597     Renton  WA 98059     USA
4598    Seattle  WA 98178     USA
4599  Covington  WA 98042     USA

[4600 rows x 18 columns]>

In [4]:
house_data.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [5]:
house_data.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [6]:
print(house_data["waterfront"].value_counts())
print(house_data["country"].value_counts())
print(house_data["city"].value_counts())

waterfront
0    4567
1      33
Name: count, dtype: int64
country
USA    4600
Name: count, dtype: int64
city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Kirkland                187
Issaquah                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
Tukwila                  29
SeaTac                   29
Vashon                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Clyde Hill               11
Fall City                11
Medina                   11
Black Diamond             9
Ravensdale                7
Pacific                   6
Algona                    5
Yarrow Point              4
Skykomish                 3
Milton                    2
Preston                   2
Inglewood-Finn Hill       1
Snoqualmie Pass           1
Beaux Arts Village        1
Name: count, dtype: int64

# Drop unneccesary Columns

In [7]:
house_data = house_data.drop(columns = ["date", "country", "street"])

# Handle StateZip columns which has Alphanumerical Value

In [8]:
house_data[['state', 'zip']] = house_data['statezip'].str.split(' ',expand = True)
house_data = house_data.drop(columns = ['statezip', 'state'])
house_data

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,zip
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,Shoreline,98133
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,Seattle,98119
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,Kent,98042
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,Bellevue,98008
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,Redmond,98052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,Seattle,98133
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,Bellevue,98007
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,Renton,98059
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,Seattle,98178
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,Covington,98042

# Standarization

In [9]:
scaler = StandardScaler()
numerical_column = ["bedrooms",	'bathrooms', 'sqft_living',	'sqft_lot',	'floors', 'waterfront',	'view',	'condition', 'sqft_above',	'sqft_basement',	'yr_built',	'yr_renovated', 'zip'	]

house_data[numerical_column] = scaler.fit_transform(house_data[numerical_column])
house_data

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,zip
0,3.130000e+05,-0.441122,-0.843204,-0.829971,-0.193434,-0.022416,-0.085004,-0.309194,-0.667112,-0.565224,-0.672464,-0.531014,1.221670,Shoreline,1.009107
1,2.384000e+06,1.759705,0.432802,1.568528,-0.161718,0.906555,-0.085004,4.830079,2.286416,1.789559,-0.069128,-1.674693,-0.825693,Seattle,0.745633
2,3.420000e+05,-0.441122,-0.205201,-0.217367,-0.080978,-0.951388,-0.085004,-0.309194,0.809652,0.119171,-0.672464,-0.161000,-0.825693,Kent,-0.703469
3,4.200000e+05,-0.441122,0.113800,-0.144686,-0.190145,-0.951388,-0.085004,-0.309194,0.809652,-0.959621,1.482306,-0.261913,-0.825693,Bellevue,-1.343333
4,5.500000e+05,0.659291,0.432802,-0.206984,-0.121306,-0.951388,-0.085004,-0.309194,0.809652,-0.797222,1.051352,0.175376,1.208396,Redmond,-0.515274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,-0.441122,-0.524202,-0.653458,-0.236689,-0.951388,-0.085004,-0.309194,0.809652,-0.368025,-0.672464,-0.564651,1.195121,Seattle,1.009107
4596,5.343333e+05,-0.441122,0.432802,-0.705374,-0.202882,0.906555,-0.085004,-0.309194,-0.667112,-0.426025,-0.672464,0.410840,1.225755,Bellevue,-1.362153
4597,4.169042e+05,-0.441122,0.432802,0.904009,-0.218462,0.906555,-0.085004,-0.309194,-0.667112,1.371962,-0.672464,1.285418,-0.825693,Renton,-0.383538
4598,2.034000e+05,0.659291,-0.205201,-0.051238,-0.229164,-0.951388,-0.085004,-0.309194,-0.667112,-0.878421,1.525401,0.108101,-0.825693,Seattle,1.855985
4599,2.206000e+05,-0.441122,0.432802,-0.674224,-0.188139,0.906555,-0.085004,-0.309194,0.809652,-0.391225,-0.672464,0.646303,-0.825693,Covington,-0.703469

# Get Dummies of the Different cities

In [10]:
counts = house_data['city'].value_counts()

In [11]:
house_data['city'].nunique()
threshold = 50

In [12]:
replace_remaining = counts[counts <= threshold].index

In [13]:
city_encoded = pd.get_dummies(house_data['city'].replace(replace_remaining, "Other"),dtype = int)

In [14]:
city_encoded

,Auburn,Bellevue,Burien,Des Moines,Federal Way,Issaquah,Kenmore,Kent,Kirkland,Maple Valley,Mercer Island,Other,Redmond,Renton,Sammamish,Seattle,Shoreline,Snoqualmie,Woodinville
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4596,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4597,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4598,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4599,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [15]:
print(house_data.shape)
print(city_encoded.shape)

(4600, 15)
(4600, 19)

In [ ]:
# Merse Main Dataset of house that is house_data and city encoded data that is city_encoded

In [16]:
house_data = house_data.reset_index(drop = True)
city_encoded = city_encoded.reset_index(drop = True)

In [17]:
house_data = pd.concat([house_data, city_encoded], axis = 1)

In [18]:
house_data = house_data.drop(columns = ['city'])

# Train Test split

In [19]:
X_train, X_test, y_train, y_test = train_test_split((house_data.drop(columns = ["price"])),house_data['price'], test_size = 0.3, random_state = 45)

In [20]:
X_train.head(5)

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,...,Maple Valley,Mercer Island,Other,Redmond,Renton,Sammamish,Seattle,Shoreline,Snoqualmie,Woodinville
3617,0.659291,0.432802,0.052594,-0.093436,-0.951388,-0.085004,-0.309194,0.809652,-0.460825,0.965161,...,0,0,0,0,0,0,0,0,0,0
4159,0.659291,0.432802,0.488684,-0.270690,0.906555,-0.085004,-0.309194,-0.667112,0.907965,-0.672464,...,0,0,0,0,0,0,1,0,0,0
2060,1.759705,0.751803,2.347262,0.101656,-0.951388,-0.085004,3.545261,2.286416,0.490369,3.960291,...,0,0,0,0,0,0,0,0,0,0
2767,-0.441122,-0.205201,-0.123919,-0.260657,-0.022416,-0.085004,3.545261,-0.667112,-0.043228,-0.176867,...,0,0,0,0,0,0,1,0,0,0
1591,0.659291,0.432802,-0.103153,0.217402,0.906555,-0.085004,-0.309194,-0.667112,0.246770,-0.672464,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
# Model Traning

In [24]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Model Evalution

In [34]:
X_train_prediction = model.predict(X_train)
mae_train = mean_absolute_error(y_train, X_train_prediction)
mae_train

149103.80972615568

In [36]:
X_test_prediction = model.predict(X_test)
mae_test = mean_absolute_error(y_test, X_test_prediction)
mae_test

143179.00353511676

In [37]:
from sklearn.metrics import r2_score

r2_train = r2_score(y_train, X_train_prediction)
r2_test = r2_score(y_test, X_test_prediction)

print(r2_train)
print(r2_test)

0.21753759401237605
0.5373332898253429