In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df=pd.read_csv("C:\\Users\\jiyad\\OneDrive\\Desktop\\stastics.com.csv")
df

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2,39.07,2,3699
1,Chikka Tirupathi,4 Bedroom,2600.0,5,120.00,4,4615
2,Uttarahalli,3 BHK,1440.0,2,62.00,3,4305
3,Lingadheeranahalli,3 BHK,1521.0,3,95.00,3,6245
4,Kothanur,2 BHK,1200.0,2,51.00,2,4250
...,...,...,...,...,...,...,...
13195,Whitefield,5 Bedroom,3453.0,4,231.00,5,6689
13196,other,4 BHK,3600.0,5,400.00,4,11111
13197,Raja Rajeshwari Nagar,2 BHK,1141.0,2,60.00,2,5258
13198,Padmanabhanagar,4 BHK,4689.0,4,488.00,4,10407
13199,Doddathoguru,1 BHK,550.0,1,17.00,1,3090

In [4]:
df.head()

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2,39.07,2,3699
1,Chikka Tirupathi,4 Bedroom,2600.0,5,120.00,4,4615
2,Uttarahalli,3 BHK,1440.0,2,62.00,3,4305
3,Lingadheeranahalli,3 BHK,1521.0,3,95.00,3,6245
4,Kothanur,2 BHK,1200.0,2,51.00,2,4250

In [11]:
mean=np.mean(df["price_per_sqft"])
print(mean)

7920.336742424242

In [49]:
import random
import pandas as pd

In [59]:
data={"price":[]}
lists=[]
for i in range(50):
    j=random.choice(df["price_per_sqft"])
    lists.append(j)
new=data.update({"price":lists})
df2=pd.DataFrame(data)   
df2

    price
0    8174
1    2909
2    6466
3    3980
4    9132
5    5558
6    8055
7    7500
8    6736
9    3733
10   4111
11   7100
12   3389
13  20833
14  15555
15  14583
16   4484
17   4952
18   2982
19   6183
20   2964
21   3756
22  13750
23   5454
24  10000
25   7916
26   7000
27  13750
28   3121
29   4444
30   7542
31   4847
32   4262
33   4285
34   4500
35   5999
36   6349
37   8250
38   6805
39   2550
40   4504
41   5208
42   9580
43   6701
44  26000
45  10967
46   4458
47   3200
48   5380
49  11206

In [68]:
mean=df2.mean()
print("mean : ",mean)

mean :  price    7223.26
dtype: float64