In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("C:\\Datasets_ml\\placement-dataset.csv")
dataset

           city  cgpa     iq  placement
0      New York   6.8  123.0          1
1   Los Angeles   5.9  106.0          0
2       Chicago   NaN  121.0          0
3      New York   7.4  132.0          1
4   Los Angeles   5.8  142.0          0
..          ...   ...    ...        ...
95      Chicago   4.3  200.0          0
96     New York   4.4   42.0          0
97  Los Angeles   6.7  182.0          1
98      Chicago   6.3  103.0          1
99     New York   6.2  113.0          1

[100 rows x 4 columns]

In [3]:
dataset.isnull().sum()

city         0
cgpa         8
iq           4
placement    0
dtype: int64

In [4]:
dataset.isnull()

     city   cgpa     iq  placement
0   False  False  False      False
1   False  False  False      False
2   False   True  False      False
3   False  False  False      False
4   False  False  False      False
..    ...    ...    ...        ...
95  False  False  False      False
96  False  False  False      False
97  False  False  False      False
98  False  False  False      False
99  False  False  False      False

[100 rows x 4 columns]

In [5]:
dataset.head(50)

           city  cgpa     iq  placement
0      New York   6.8  123.0          1
1   Los Angeles   5.9  106.0          0
2       Chicago   NaN  121.0          0
3      New York   7.4  132.0          1
4   Los Angeles   5.8  142.0          0
5       Chicago   7.1   48.0          1
6      New York   5.7    NaN          0
7   Los Angeles   5.0   63.0          0
8       Chicago   6.1  156.0          0
9      New York   5.1   66.0          0
10  Los Angeles   6.0   45.0          1
11      Chicago   6.9  138.0          1
12     New York   5.4  139.0          0
13  Los Angeles   6.4  116.0          1
14      Chicago   NaN  103.0          0
15     New York   5.1  176.0          0
16  Los Angeles   5.2  224.0          0
17      Chicago   3.3  183.0          0
18     New York   4.0    NaN          0
19  Los Angeles   5.2  132.0          0
20      Chicago   6.6  120.0          1
21     New York   7.1  151.0          1
22  Los Angeles   4.9  120.0          0
23      Chicago   NaN   87.0          0
24     New York   4.7  121.0          0
25  Los Angeles   5.0   91.0          0
26      Chicago   7.0  199.0          1
27     New York   6.0  124.0          1
28  Los Angeles   5.2   90.0          0
29      Chicago   NaN    1.0          0
30     New York   7.6  128.0          1
31  Los Angeles   3.9  109.0          0
32      Chicago   7.0  139.0          1
33     New York   6.0  149.0          0
34  Los Angeles   4.8  163.0          0
35      Chicago   6.8   90.0          1
36     New York   5.7  140.0          0
37  Los Angeles   8.1  149.0          1
38      Chicago   6.5  160.0          1
39     New York   4.6  146.0          0
40  Los Angeles   4.9  134.0          0
41      Chicago   5.4  114.0          0
42     New York   7.6   89.0          1
43  Los Angeles   NaN  141.0          1
44      Chicago   7.5   61.0          1
45     New York   6.0   66.0          1
46  Los Angeles   5.3  114.0          0
47      Chicago   5.2  161.0          0
48     New York   6.6  138.0          1
49  Los Angeles   5.4  135.0          0

In [6]:
from sklearn.impute import SimpleImputer
s1 = SimpleImputer(strategy = "mean")
arr_num = np.round(s1.fit_transform(dataset[["cgpa","iq"]]),2)
dataset2 = pd.DataFrame(arr_num)
dataset2

       0      1
0   6.80  123.0
1   5.90  106.0
2   5.97  121.0
3   7.40  132.0
4   5.80  142.0
..   ...    ...
95  4.30  200.0
96  4.40   42.0
97  6.70  182.0
98  6.30  103.0
99  6.20  113.0

[100 rows x 2 columns]

In [8]:
dataset.drop(['cgpa','iq'],inplace = True,)

KeyError: "['cgpa', 'iq'] not found in axis"