In [1]:
import pandas as pd
import matplotlib.pyplot a

In [2]:
#Program 2 — Fill Missing Values in Temperature Dataset

"""Problem:
A temperature sensor failed on some days.
Fill missing values using the mean temperature."""


df={
    "Dataset": [30, 32, None, 29, 28, None, 31]
}
df

{'Dataset': [30, 32, None, 29, 28, None, 31]}

In [3]:
data=pd.DataFrame(df)
data

   Dataset
0     30.0
1     32.0
2      NaN
3     29.0
4     28.0
5      NaN
6     31.0

In [4]:
update=data.fillna(30)
update

   Dataset
0     30.0
1     32.0
2     30.0
3     29.0
4     28.0
5     30.0
6     31.0

In [7]:
#Program 3 — Compare Product Performance
"""Problem:
Two products A and B are compared for sales performance over 6 months.
Show which product sold better and plot side-by-side."""

product={
    "Product_A":[200,250,300,280,270,290],
    "Product_B":[180,220,260,300,320,310]
}
product

{'Product_A': [200, 250, 300, 280, 270, 290],
 'Product_B': [180, 220, 260, 300, 320, 310]}

In [3]:
data=pd.DataFrame(product)
data

NameError: name 'pd' is not defined

In [4]:
data.index=[1,2,3,4,5,6]

NameError: name 'data' is not defined